//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public int IDCTDonHang { get; set; }
        public Nullable<int> IDDonHang { get; set; }
        public Nullable<int> IDSanpham { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
