//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDonHang = new HashSet<CTDonHang>();
            this.ThongKe = new HashSet<ThongKe>();
        }
    
        public int IDDonHang { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public Nullable<double> TongSoLuong { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<decimal> TongThanhTien { get; set; }
        public Nullable<decimal> TienTraLai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKe> ThongKe { get; set; }
    }
}
