//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKyThuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoKyThuat()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int IDThongso { get; set; }
        public string ManHinh { get; set; }
        public string HDH { get; set; }
        public string CameraSau { get; set; }
        public string CameraTruoc { get; set; }
        public string Chip { get; set; }
        public string Ram { get; set; }
        public string DungLuong { get; set; }
        public string Sim { get; set; }
        public string Pin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
